{application,csvparser,
             [{applications,[kernel,stdlib,elixir,logger,mariaex,ecto,csv]},
              {description,"csvparser"},
              {modules,['Elixir.Csvparser','Elixir.Csvparser.Konsumen',
                        'Elixir.Csvparser.Repo']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger,mariaex,ecto]},
              {mod,{'Elixir.Csvparser',[]}}]}.
